# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1324e9f3639ed3de0308b837617a54e52cdd3f8d74b322406983d4f60c2c70f05fe16d42daaac358a29cab290014082db5a134413daf3a6b28f48da18bba0f34

test:
  secret_key_base: f6708320dcc3eb5287346807da5c92e3b480855f1cf2c92fdd7830eff88f3ee24db0799220c7ac19a32a089547a4fd6646541b6d42102491bebd4089e0e8d66a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
